config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :users, only: %i[new create destroy]
  resources :articles do
    resources :comments, only: %i[create destroy], shallow: true
    resource :favorite, only: %i[create destroy]
    post :confirm_category, action: :confirm_category, on: :new
    get 'index_user', on: :collection
  end
  resources :favorite_articles, only: :index

  get 'category_list', to: 'articles#category_list'
  root 'articles#index'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'terms', to: 'settings#terms'
  get 'privacy_policy', to: 'settings#privacy_policy'
  get '*path', to: 'application#render404'
end

app/models/comment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  body       :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  article_id :bigint
#  user_id    :bigint
#
# Indexes
#
#  index_comments_on_article_id  (article_id)
#  index_comments_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (article_id => articles.id)
#  fk_rails_...  (user_id => users.id)
#
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :body, presence: true, length: { maximum: 65_535 }
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def create
    comment = current_user.comments.build(comment_params)
    if comment.save
      redirect_to article_path(comment.article), notice: t('defaults.success', item: Comment.model_name.human)
    else
      redirect_to article_path(comment.article), notice: t('defaults.fail', item: Comment.model_name.human)
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
    redirect_to article_path(@comment.article), notice: t('defaults.deleted', item: Comment.model_name.human)
  end

  private

    def comment_params
      params.require(:comment).permit(:body).merge(article_id: params[:article_id])
    end
end

app/views/comments/_comment.html.haml
%section.mt-1.lg:grid-cols-4.gap-x-6.gap-y-8.mx-4
  %article.bg-yellow-50.group.relative.rounded-lg.overflow-hidden.shadow-lg.transform.duration-200.h-40.mt-8
    .flex-grow
      %ul
        %li
          %h3.text-yellow-500.inline-flex.items-center.ml-4.mt-4.md:text-xl.sm:text-3xl
            = comment.user.name
          %h2.text-gray-900.text-lg.title-font.font-medium.mb-3.ml-4.md:text-xl.sm:text-3xl
            = comment.body
          .text-right.mr-8
            - if current_user.own?(comment)
              = link_to icon("fas", "trash-alt", class: "fa-thin"), comment_path(comment), method: :delete,
                                          data: { confirm: '削除してよろしいですか？' }

app/views/comments/_comments.html.haml
- if comments.present?
  = render comments

app/views/comments/_form.html.haml
%section.mt-1.lg:grid-cols-4.gap-x-6.gap-y-8.mx-4
  = form_with model: comment, url: [article,comment], local: true do |f|
    = render 'shared/error_messages', object: f.object
    .text-center.mt-4.bg-white.rounded.border.border-yellow-500.mb-8
      = f.text_area :body, :size=>"80x3"
    .mb-12
      = f.submit 'コメントする', class: 'bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded mx-auto flex justify-center'