config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :users, only: %i[new create destroy]
  resources :articles do
    resources :comments, only: %i[create destroy], shallow: true
    resource :favorite, only: %i[create destroy]
    post :confirm_category, action: :confirm_category, on: :new
    get 'index_user', on: :collection
  end
  resources :favorite_articles, only: :index

  get 'category_list', to: 'articles#category_list'
  root 'articles#index'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'terms', to: 'settings#terms'
  get 'privacy_policy', to: 'settings#privacy_policy'
  get '*path', to: 'application#render404'
end

app/models/article.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: articles
#
#  id          :bigint           not null, primary key
#  description :text
#  image       :string           not null
#  title       :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :bigint           not null
#  user_id     :bigint
#
# Indexes
#
#  index_articles_on_category_id  (category_id)
#  index_articles_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#  fk_rails_...  (user_id => users.id)
#
class Article < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_articles, through: :favorites, source: :article

  validates :title, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 300 }
  validates :image, presence: true
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  skip_before_action :require_login, only: :index
  before_action :set_article, only: [:edit, :update, :destroy]

  def index
    @articles = Article.all.includes([:user, :favorites]).order(created_at: :desc).page(params[:page]).per(5)
  end

  def new
    if params[:confirm_back]
      @article.image.retrieve_from_cache!(session[:image_cache_name])
    else
      @article = Article.new
    end
  end

  def confirm_category
    @article = current_user.articles.build(article_params)
    if params[:article][:image].present?
      temp_image = TemporaryRekognitionImage.create(source: params[:article][:image])
      @result = image_rekognition(temp_image.source)
    end
    render :new unless valid_except_category(@article)
  end

  def create
    @article = current_user.articles.build(article_params)
    @article.image.retrieve_from_cache! params[:cache][:image]

    if params[:back].present?
      render :new
      return
    end

    if @article.save(validate: false)
      redirect_to articles_path, notice: t('defaults.success', item: Article.model_name.human)
    else
      flash.now['notice'] = t('defaults.faile', item: Article.model_name.human)
      render :new
    end
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comments = @article.comments.includes(:user).order(created_at: :desc)
  end

  def edit; end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: t('defaults.updated', item: Article.model_name.human)
    else
      flash.now[:notice] = t('defaults.no_updated', item: Article.model_name.human)
      render :edit
    end
  end

  def destroy
    @article.destroy!
    redirect_to articles_path, notice: t('defaults.deleted', item: Article.model_name.human)
  end

  def category_list
    if params[:category_id].present?
      @categories = Article.where(category_id: params[:category_id]).includes([:user, :favorites,
                                                                               :category]).order(created_at: :desc).page(params[:page]).per(5)
    else
      render :index
    end
  end

  def index_user
    @articles = current_user.articles.includes([:user, :favorites, :category]).order(created_at: :desc).page(params[:page]).per(5)
  end

  private

    def article_params
      params.require(:article).permit(:title, :description, :image, :category_id)
    end

    def set_article
      @article = current_user.articles.find(params[:id])
    end

    def valid_except_category(article)
      article.valid?
      article.errors.delete(:category)
      article.errors.empty?
    end

    def image_rekognition(image)
      Aws.config.update({
                          region: 'ap-northeast-1',
                          credentials: Aws::Credentials.new(Rails.application.credentials.aws[:access_key_id],
                                                            Rails.application.credentials.aws[:secret_access_key])
                        })

      rekognition = Aws::Rekognition::Client.new(region: Aws.config[:region], credentials: Aws.config[:credentials])
      response = rekognition.detect_labels({
                                             image: {
                                               s3_object: {
                                                 bucket: 'photo-app-0207',
                                                 name: image.path
                                               }
                                             }
                                           })

      result_label_list = response.labels
      uper_confidence_list = result_label_list.select do |result_label|
        result_label.confidence >= 90
      end

      rekognition_name_list = uper_confidence_list.map(&:name)

      category_name_list = Category.pluck(:rekognition_name)
      rekognition_name_result = 'その他'
      rekognition_name_list.each do |rekogniton_name|
        category = category_name_list.find { |category_name| category_name == rekogniton_name }
        if category.present?
          rekognition_name_result = category
          break
        end
      end

      Category.find_by(rekognition_name: rekognition_name_result)
    end
end

app/views/articles/_article.html.haml
.flex.mt-12
  %article.bg-white.group.relative.rounded-lg.overflow-hidden.shadow-lg.mb-12.white-board.grid.grid-cols-1.sm:grid-cols-2.md:grid-cols-3
    %h2.md:text-xl.sm:text-6xl.font-extrabold.text-gray-600.text-center.mt-16
      = link_to article.title, article_path(article)
    .relative.flex.justify-center.my-8
      = image_tag article.image.to_s
    .px-3.py-4
      %h3.text-sm.text-gray-500.pb-2
      - if article.description.present?
        %p.md:text-xl.sm:text-3xl.text-base.text-gray-600
          = safe_join(article.description.split("\n"))
      %p.md:text-xl.sm:text-3xl.text-base.text-gray-600.text-right
        = l article.created_at, format: :long
      %p.md:text-xl.sm:text-3xl.text-base.text-gray-600.text-right
        = safe_join(article.user.name.split("\n"))
      .flex.flex-wrap.justify-center.my-8
        - if logged_in?
          - if current_user.own?(article)
            .md:text-xl.sm:text-3xl.text-yellow-500.my-4.mx-4
              = link_to icon("fas", "edit", class: "edit"), edit_article_path(article)
            .md:text-xl.sm:text-3xl.text-yellow-500.my-4.mx-4
              = link_to icon("fas", "trash-alt", class: "fa-thin"), article_path(article),
                method: :delete,
                data: { confirm: t('defaults.delete_confirm') }
          - else
            = render 'articles/favorite_button', { article: article }

app/views/articles/_category_choice.html.haml
.bg-yellow-100.pt-10.text-center
  = form_with model: article, url: category_list_path, method: :get, local: true do |f|
    .ml-8.mt-4.md:text-2xl.sm:text-3xl
      %p= t('defaults.choice_category')
    .text-base
      = f.collection_select :category_id, Category.all, :id, :display_name, { include_blank: "選択してください" }
    .my-8
      = f.submit t('defaults.choice_category_button'), class: 'bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded'
  - if articles.present?
    = render articles
    .md:text-base.sm:text-2xl
      = paginate articles
  - else
    .bg-green-100.border.border-yellow-500.text-green-700.px-4.py-3.rounded.mx-10.my-10
      %p= t('defaults.no_article')

app/views/articles/_edit_article.html.haml
= form_with model: article, local: true do |f|
  = render 'shared/error_messages', object: f.object
  .md:text-xl.sm:text-3xl
    = f.label :title
  .bg-white.rounded.border.border-green-500.mb-8.md:text-xl.sm:text-3xl
    = f.text_area :title, :size=>"80x2", id: 'article_title'
  .focus:border-indigo-300.py-6.md:text-xl.sm:text-3xl
    = f.label :description
    %br
    .bg-white.rounded.border.border-green-500.mb-8.text-center.md:text-xl.sm:text-3xl
      = f.text_area :description, :size=>"80x20", id: 'article_description'
    = f.submit t('defaults.update'), class: 'bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded mx-auto flex justify-center'

app/views/articles/_favorite.html.haml
= link_to article_favorite_path(article.id),
            id: "js-favorite-button-for-article-#{article.id}",
            method: :delete,
            remote: true do
  .md:text-xl.sm:text-3xl
    = icon("fas", "fa-heart", class: "fa-heart")

app/views/articles/_favorite_button.html.haml
- if current_user.favorite?(article)
  = render 'articles/favorite', { article: article }
- else
  = render 'articles/unfavorite', { article: article }

app/views/articles/_form.html.haml
= form_with model: article, local: true, url: confirm_category_new_article_path do |f|
  = render 'shared/error_messages', object: f.object
  .md:text-xl.sm:text-3xl
    = f.label :title
  .inputWithIcon
    .bg-white.rounded.border.border-green-500.mb-8.md:text-xl.sm:text-3xl
      = f.text_area :title, id: 'article_title'
  .focus:border-indigo-300.focus:ring.focus:ring-indigo-200.focus:ring-opacity-50.mt-4.md:text-xl.sm:text-3xl
    = f.label :image
  .focus:border-indigo-300.focus:ring.focus:ring-indigo-200.focus:ring-opacity-50.mt-4.md:text-xl.sm:text-3xl
    = f.file_field :image, id: 'article_image'
  .text-green-600.md:text-xl.sm:text-3xl
    %p ※jpeg/jpg/png形式の画像を添付してください
  .focus:border-indigo-300.py-6.md:text-xl.sm:text-3xl
    = f.label :description
    %br
      .inputWithIcon
        .bg-white.rounded.border.border-green-500.mb-8.text-center.md:text-xl.sm:text-3xl
          = f.text_area :description, :size=>"60x20", id: 'article_description'
    = f.submit t('defaults.register'), class: 'bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded mx-auto flex justify-center'

app/views/articles/_unfavorite.html.haml
= link_to article_favorite_path(article.id),
            id: "js-favorite-button-for-article-#{article.id}",
            method: :post,
            remote: true do
  .md:text-xl.sm:text-3xl
    = icon("far", "fa-heart", class: "fa-heart")

app/views/articles/category_list.html.haml
.bg-yellow-100
  = form_with model: @article, url: category_list_path, method: :get, local: true do |f|
    .ml-8.mt-4.mb-8.md:text-xl.sm:text-3xl
      %p= t('defaults.choice_category')
      .md:text-xl.sm:text-2xl
        = f.collection_select :category_id, Category.all, :id, :display_name, { include_blank: "選択してください" }
        = f.submit t('defaults.choice_category_button'), class: 'bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded'
  - if @categories.present?
    - @categories.each do |article|
      = render 'article', { article: article }
  - else
    .bg-green-100.border.border-yellow-500.text-green-700.px-4.py-3.rounded.mx-10.my-10
      %p= t('defaults.no_article')

app/views/articles/confirm_category.html.haml
.flex.flex-col.min-h-screen
  %main.flex-grow.bg-yellow-100.bg-white.rounded.overflow-hidden.shadow-lg.p-8.rounded-lg.mx-8.my-8
    = form_with model: @article, local: true  do |f|
      %article.bg-white.group.relative.rounded-lg.overflow-hidden.shadow-lg.mb-12
        %h2.text-xl.font-extrabold.text-gray-600.text-center.mt-16md:text-3xl.sm:text-4xl.mt-12
          = @article.title
          = f.hidden_field :title
          - if @article.description.present?
            .md:text-xl.sm:text-3xl
              = @article.description
              = f.hidden_field :description
        .relative.w-full.h-80.md:h-64.lg:h-44.flex.justify-center.mt-8
          = image_tag @article.image.url
          = hidden_field_tag :'cache[image]', @article.image.cache_name
        %p.text-xl.text-base.text-gray-600.group-hover:text-indigo-600.text-center.mt-8.md:text-xl.sm:text-3xl
          = safe_join(@article.user.name.split("\n"))
        .relative.w-full.h-80.md:h-64.lg:h-44.flex.justify-center.mt-8
          .focus:border-indigo-300.focus:ring.focus:ring-indigo-200.focus:ring-opacity-50.mt-4.ml-12.md:text-xl.sm:text-3xl
            = f.label :category_id
            = f.collection_select :category_id, Category.all, :id, :display_name, {selected: @result.id}
        %p.text-xl.text-base.font-semibold.text-red-600.text-center.mb-8
          = t('defaults.select_category_again')
        .my-8.mb-8
          = f.submit t('defaults.back'), name: 'back', class: 'bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded mx-auto flex justify-center'
        .my-8.mb-8
          = f.submit t('defaults.register'), class: 'bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded mx-auto flex justify-center'

app/views/articles/edit.html.haml
- provide(:title, 'Edit')
%main.flex-grow.bg-green-100.bg-white.rounded.overflow-hidden.shadow-lg.p-8.rounded-lg.mx-8.my-8
  = render 'edit_article', { article: @article }
  .flex.flex-col.mt-8

app/views/articles/favorites.html.haml
.bg-yellow-100.pt-10
  - if @favorite_articles.present?
    - @favorite_articles.each do |article|
      = render 'article', { article: article }

app/views/articles/index.html.haml
- provide(:title, 'Top Page')
.text-center.sm:text-center
  = render 'category_choice', { article: @article, articles: @articles }

app/views/articles/new.html.haml
- provide(:title, 'New')
.flex.flex-col.min-h-screen
  %main.flex-grow.bg-yellow-100.bg-white.rounded.overflow-hidden.shadow-lg.p-8.rounded-lg.mx-8.my-8
    = render 'form', { article: @article }
  %section.max-w-7xl.mx-auto.px-4.sm:px-6.lg:px-4.mt-12.mb-12
    %section.mt-6.grid.md:grid-cols-2.lg:grid-cols-4.gap-x-6.gap-y-8

app/views/articles/show.html.haml
- provide(:title, t('.show_page'))
.bg-yellow-100.pt-10
  = render @article
  .md:text-xl.sm:text-3xl.white-board
    = render 'comments/comments', { comments: @comments }
    = render 'comments/form', { article: @article, comment: @comment }