config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :users, only: %i[new create destroy]
  resources :articles do
    resources :comments, only: %i[create destroy], shallow: true
    resource :favorite, only: %i[create destroy]
    post :confirm_category, action: :confirm_category, on: :new
    get 'index_user', on: :collection
  end
  resources :favorite_articles, only: :index

  get 'category_list', to: 'articles#category_list'
  root 'articles#index'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'terms', to: 'settings#terms'
  get 'privacy_policy', to: 'settings#privacy_policy'
  get '*path', to: 'application#render404'
end

app/views/shared/_before_login_header.html.haml
%header.text-yellow-500.body-font
  .container.mx-auto.flex.flex-wrap.p-5.flex-col.md:flex-row.items-center
    %a.flex.title-font.font-medium.text-center.text-yellow-500.md:mb-0
      = link_to image_tag('animagram_rectangle.png', size: '320x240'), articles_path
    %nav.md:ml-auto.flex.flex-wrap.items-center.text-base.justify-center
      %nav
        .hamburger
          %span
          %span
          %span
        %nav.globalMenuSp
          %ul
            %li
              .md:text-base.sm:text-3xl
                = link_to t('users.new.register'), new_user_path
            %li
              .md:text-base.sm:text-3xl
                = link_to t('defaults.login'), login_path

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  .alert.alert-warning
    %ul
      .sm:text-3xl
        - object.errors.full_messages.each do |message|
          %li= message

app/views/shared/_flash_message.html.haml
.notifications
  - flash.each do |key, value|
    .bg-green-100.border.border-yellow-500.text-green-700.px-4.py-3.rounded.mx-10.my-16.sm:text-3xl.md:text-xl
      = content_tag(:div, value, class: key)

app/views/shared/_footer.html.haml
%footer.bg-white.bottom-0
  .text-gray-500.body-font
    %p.md:text-base.sm:text-2xl.text-gray-500.sm:ml-4.sm:pl-4.sm:border-1-2.sm:border-gray-200.sm:py-2.sm:mt-0.mt-4.ml-4
      = link_to '利用規約', terms_path
    %p.md:text-base.sm:text-2xl.text-gray-500.sm:ml-4.sm:pl-4.sm:border-1-2.sm:border-gray-200.sm:py-2.sm:mt-0.mt-8.ml-4
      = link_to 'プライバシーポリシー', privacy_policy_path
    %svg.w-5.h-5.mt-8.ml-8{"fill" => "currentColor", "stroke" => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2", "viewBox" => "0 0 24 24" }
      %path{"d" => "M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"}

  %p.md:text-base.sm:text-2xl.text-gray-500.sm:border-l-2.sm:border-gray-200.sm:py-4.sm:mt-0.mb-4.sm:text-center.mt-4.mb-8.text-center
    © 2022 animagram

app/views/shared/_header.html.haml
%header.text-yellow-500.body-font.m-auto
  .container.flex.justify-center.p-5.mx-auto.text-center
    %a.flex.title-font.font-medium.items-center.text-yellow-500.md:mb-0
      = link_to image_tag('animagram_rectangle.png', size: '320x240'), articles_path, class: 'text-center'
    %nav.md:ml-auto.flex.flex-wrap.items-center.text-base.justify-center.mb-4
    #navArea
      %nav
        .hamburger
          %span
          %span
          %span
        %nav.globalMenuSp
          %ul
            %li
              .md:text-base.sm:text-3xl
                = link_to t('defaults.up_article'), new_article_path
            %li
              .md:text-base.sm:text-3xl
                = link_to t('defaults.index_user_articles'), index_user_articles_path
            %li
              .md:text-base.sm:text-3xl
                = link_to t('favorite_articles.index.articles_list'), favorite_articles_path
            %li
              .md:text-base.sm:text-3xl
                = link_to t('defaults.top'), root_path
            %li
              .md:text-base.sm:text-3xl
                = link_to t('user_sessions.new.logout'), logout_path, method: :delete